### ISSUE TITLE
XCode 4.3 issue; iPhone sim fails to launch

### ISSUE THREAD

**Issue by robfromca** [moredip/Sim-Launcher#2]
Even after updating to 0.3.7, the iPhonesim binary fails because of some path issues finding frameworks.

$ ./iphonesim "showsdks" 
dyld: Library not loaded: @rpath/iPhoneSimulatorRemoteClient.framework/Versions/A/iPhoneSimulatorRemoteClient
  Referenced from: /Users/xxx/.rvm/gems/ruby-1.9.3-p0@xxxxxx/gems/sim_launcher-0.3.7/lib/sim_launcher/../../native/iphonesim
  Reason: image not found
Trace/BPT trap: 5

Was working fine with Xcode 4.2. When I pull the source separately for iphonesim and build it with Xcodebuild, it works okay. (I did that, and dropped it into the gem directory as a workaround, so this isn't urgent).

**Comment by moredip** [comment]
Thanks for reporting this Rob. FYI there has been discussion of this on the Frank mailing list too: http://groups.google.com/group/frank-discuss/browse_thread/thread/2a34c5b080ea6b78.

**Comment by moredip** [comment]
Pull request #3 should resolve this. Please report back if that's not the case.
