### ISSUE TITLE
fatal reference in iphonesim submodule

### ISSUE THREAD

**Issue by jmoody** [moredip/Sim-Launcher#29]
I made a fork and tried to clone:

```
$ git clone --recursive git@github.com:jmoody/Sim-Launcher.git
fatal: reference is not a tree: a18578003f52c6da7b543a6981d66937b289477c
Unable to checkout 'a18578003f52c6da7b543a6981d66937b289477c' in submodule path 'vendor/iphonesim'
```

I am a calabash-ios/android maintainer and would like to make a pull request (minor change) on this repo.

Cheers.

**Comment by moredip** [comment]
2115c94a5933660f843ca49cc645f7ab313d5b9e should have fixed this. 

Looks like I accidentally pointed to an iphonesim commit which hadn't been pushed to github. Sorry about that.

**Comment by jmoody** [comment]
no worries.  it happens. :)

thanks for the quick fix.
