### ISSUE TITLE
is not working with iOS8

### ISSUE THREAD

**Issue by dianapapyan** [moredip/Sim-Launcher#32]
can you also add iOS8 support please?

Thanks,
Diana.

**Comment by ctews** [comment]
There is a segmentation fault occuring with the newest iOS 8 SDK (XCode Beta 6). Could you please try to fix this issue?
Using iPhoneSimulator 7 here with newest iOS8 SDK is by intention.

Thank in advance! :)

```
sh: line 1: 20995 Trace/BPT trap: 5       /Users/ctews/.rvm/gems/ruby-1.9.3-p327/gems/sim_launcher-0.4.11/lib/sim_launcher/../../native/ios-sim "showsdks" 2>&1
sh: line 1: 21001 Trace/BPT trap: 5       /Users/ctews/.rvm/gems/ruby-1.9.3-p327/gems/sim_launcher-0.4.11/lib/sim_launcher/../../native/ios-sim "showsdks" 2>&1

sh: line 1: 21006 Trace/BPT trap: 5       /Users/ctews/.rvm/gems/ruby-1.9.3-p327/gems/sim_launcher-0.4.11/lib/sim_launcher/../../native/ios-sim "showsdks" 2>&1
sh: line 1: 21014 Trace/BPT trap: 5       /Users/ctews/.rvm/gems/ruby-1.9.3-p327/gems/sim_launcher-0.4.11/lib/sim_launcher/../../native/ios-sim "showsdks" 2>&1
sh: line 1: 21017 Segmentation fault: 11  /Users/ctews/.rvm/gems/ruby-1.9.3-p327/gems/sim_launcher-0.4.11/lib/sim_launcher/../../native/ios-sim "launch" "/Users/ctews/Projects/iPhone-App/build/iPhoneSimulator-7.0-Development/My.app" "--sdk" "--family" "iphone" "--exit" 2>&1
```

**Comment by MarshalGeazipp** [comment]
I also have this problem. I use the Xcode 6 GM.

```
sh: line 1: 69925 Segmentation fault: 11  /Users/hudson/.rvm/gems/ruby-2.0.0-p247/gems/sim_launcher-0.4.11/lib/sim_launcher/../../native/ios-sim "launch" "/Users/hudson/inst/mobile/workspace/MyApp.app" "--sdk" "7.1" "--family" "iphone" "--exit" 2>&1
```

**Comment by moredip** [comment]
Try installing a more recent simlauncher build using npm or homebrew. 

Cheers,

## Pete

Typed on a little bitty keyboard

**Comment by MarshalGeazipp** [comment]
It works! I installed ios-sim via npm. 
Thank you very much for your quick reply, Pete.

**Comment by moredip** [comment]
Marking this as closed, but really we should just remove the ios-sim binary from sim-launcher and require it to be installed via another mechanism to remove the need for this gem to always ship the latest and greatest.

**Comment by drekka** [comment]
Hi can we get the gem updated. Having the same problem here. Thanks

**Comment by Azat92** [comment]
I have updated ios-sim using npm but now I get an error message in browser:

Usage of '--sdk' is deprecated in 3.x. Use --devicetypeid instead. Usage of '--family' is deprecated in 3.x. Use --devicetypeid instead.

Please help. Thanks
